trigger:
- master
pool:
  vmImage: 'Ubuntu-18.04'
variables:
  image: 'pipelines-javascript-docker'
  targetRepo: 'docker-local'
steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: vigneshs-docker.jfrog.io/$(imageName)
    command: build
    Dockerfile: app/Dockerfile
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'artifactory-saas'
    targetRepo: 'docker-local'
    imageName: 'vigneshs-docker.jfrog.io/$(image):$(Build.BuildId)'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
- task: ArtifactoryProperties@1
  inputs:
    command: 'set'
    artifactoryService: 'artifactory-saas'
    setProps: 'qa=pending;os=linux;setfromado=true'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
         {
           "pattern": "$(targetRepo)/$(image):$(Build.BuildId)"
         }
        ]
      }
- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'artifactory-saas'
    buildName: $(Build.DefinitionName)
    buildNumber: $(Build.BuildNumber)