# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  repo: docker

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: vigneshs-docker.jfrog.io
        command: build
        dockerfile: '$(Build.SourcesDirectory)/app/Dockerfile'
        tags: vigneshs-docker.jfrog.io/vigneshs09jfrog.pipelines-javascript-docker:testvignesh
    - task: ArtifactoryDocker@1
      inputs:
        command: 'push'
        artifactoryService: 'artifactory-saas'
        targetRepo: 'docker'
        imageName: 'vigneshs09jfrog.pipelines-javascript-docker:testvignesh'
        collectBuildInfo: true
        buildName: '$(Build.DefinitionName)'
        buildNumber: '$(Build.BuildNumber)'
        includeEnvVars: true